type FighterKind='player'|'enemy'|'boss';
type FighterState='idle'|'walk'|'attack'|'hitstun'|'knockdown'|'getup'|'ko';
type AttackKind='jab'|'cross'|'finisher'|'enemy'|'boss';
type Phase='travel'|'combat'|'clear'|'bossIntro'|'boss'|'complete';
type Fighter={kind:FighterKind;x:number;y:number;vx:number;vy:number;width:number;height:number;health:number;maxHealth:number;facing:1|-1;state:FighterState;stateTime:number;attack?:AttackKind;attackHit:boolean;comboStep:number;comboWindow:number;hitFlash:number;think:number;id:number};
type AttackSpec={duration:number;activeFrom:number;activeTo:number;damage:number;reach:number;knockback:number;knockdown:boolean};
type Encounter={trigger:number;left:number;right:number;count:number};
const ATTACKS:Record<AttackKind,AttackSpec>={jab:{duration:.25,activeFrom:.075,activeTo:.13,damage:8,reach:92,knockback:8,knockdown:false},cross:{duration:.29,activeFrom:.09,activeTo:.16,damage:10,reach:98,knockback:12,knockdown:false},finisher:{duration:.46,activeFrom:.13,activeTo:.22,damage:18,reach:116,knockback:38,knockdown:true},enemy:{duration:.48,activeFrom:.16,activeTo:.24,damage:9,reach:78,knockback:18,knockdown:false},boss:{duration:.62,activeFrom:.2,activeTo:.31,damage:16,reach:105,knockback:30,knockdown:false}};
const ENCOUNTERS:Encounter[]=[{trigger:520,left:360,right:1050,count:2},{trigger:1250,left:1080,right:1780,count:3},{trigger:1900,left:1730,right:2230,count:4}];
export class Game{
 private readonly ctx:CanvasRenderingContext2D;private readonly keys=new Set<string>();private readonly virtualKeys=new Set<string>();private readonly pressed=new Set<string>();private previous=performance.now();private accumulator=0;private readonly fixedStep=1/60;private freezeTime=0;private shakeTime=0;private cameraX=0;private nextId=1;private encounterIndex=0;private phase:Phase='travel';private goTimer=2.6;private introTimer=0;private clearTimer=0;private readonly sprites={player:new Image(),enemy:new Image()};private readonly player:Fighter=this.make('player',180,470,1);private enemies:Fighter[]=[];
 constructor(private readonly canvas:HTMLCanvasElement){const c=canvas.getContext('2d');if(!c)throw new Error('Canvas 2D unavailable');this.ctx=c;c.imageSmoothingEnabled=false;this.sprites.player.src='/assets/fighters/alex.svg';this.sprites.enemy.src='/assets/fighters/thug.svg';window.addEventListener('keydown',e=>{if(!this.keys.has(e.code))this.pressed.add(e.code);this.keys.add(e.code);if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault()});window.addEventListener('keyup',e=>this.keys.delete(e.code))}
 private make(kind:FighterKind,x:number,y:number,facing:1|-1):Fighter{const boss=kind==='boss';return{kind,x,y,vx:0,vy:0,width:boss?78:kind==='player'?58:62,height:boss?142:kind==='player'?112:116,health:boss?260:100,maxHealth:boss?260:100,facing,state:'idle',stateTime:0,attackHit:false,comboStep:0,comboWindow:0,hitFlash:0,think:.35+Math.random()*.5,id:this.nextId++}}
 start(){requestAnimationFrame(this.frame)}setVirtualKey(code:string,down:boolean){if(down&&!this.virtualKeys.has(code))this.pressed.add(code);if(down)this.virtualKeys.add(code);else this.virtualKeys.delete(code)}private down(c:string){return this.keys.has(c)||this.virtualKeys.has(c)}private consume(c:string){const h=this.pressed.has(c);this.pressed.delete(c);return h}
 private frame=(now:number)=>{const d=Math.min((now-this.previous)/1000,.1);this.previous=now;this.accumulator+=d;while(this.accumulator>=this.fixedStep){this.update(this.fixedStep);this.accumulator-=this.fixedStep}this.render();requestAnimationFrame(this.frame)};
 private update(dt:number){if(this.freezeTime>0){this.freezeTime-=dt;this.pressed.clear();return}this.shakeTime=Math.max(0,this.shakeTime-dt);this.timers(this.player,dt);for(const e of this.enemies)this.timers(e,dt);if(this.phase==='bossIntro'){this.introTimer-=dt;if(this.introTimer<=0)this.phase='boss'}this.playerUpdate();if(this.phase!=='bossIntro')for(const e of this.enemies)this.enemyUpdate(e,dt);this.integrate(this.player,dt);for(const e of this.enemies)this.integrate(e,dt);if(this.phase==='travel'&&this.encounterIndex<ENCOUNTERS.length&&this.player.x>=ENCOUNTERS[this.encounterIndex].trigger)this.beginEncounter();if(this.phase==='combat'&&this.enemies.length>0&&this.enemies.every(e=>e.state==='ko'))this.finishEncounter();if(this.phase==='clear'){this.goTimer=Math.max(0,this.goTimer-dt);if(this.goTimer<=0)this.phase='travel'}if(this.encounterIndex>=ENCOUNTERS.length&&this.phase==='travel'&&this.player.x>=2180)this.beginBoss();if(this.phase==='boss'&&this.enemies.length&&this.enemies.every(e=>e.state==='ko')){this.phase='complete';this.clearTimer=99}this.cameraX=Math.max(0,Math.min(2300-this.canvas.width,this.player.x-this.canvas.width*.42));this.pressed.clear()}
 private beginEncounter(){const e=ENCOUNTERS[this.encounterIndex];this.phase='combat';this.goTimer=0;this.enemies=[];for(let i=0;i<e.count;i++){const side=i%2===0?1:-1;const x=Math.max(e.left+100,Math.min(e.right-100,this.player.x+side*(300+i*65)));const y=400+(i%3)*72;this.enemies.push(this.make('enemy',x,y,side>0?-1:1))}}
 private finishEncounter(){this.encounterIndex++;this.phase='clear';this.goTimer=2.6}
 private beginBoss(){this.phase='bossIntro';this.introTimer=2.3;this.goTimer=0;this.player.x=Math.min(this.player.x,2070);this.enemies=[this.make('boss',2220,465,-1)]}
 private timers(f:Fighter,dt:number){f.stateTime+=dt;f.hitFlash=Math.max(0,f.hitFlash-dt);f.comboWindow=Math.max(0,f.comboWindow-dt);if(f.comboWindow<=0&&f.state!=='attack')f.comboStep=0;if(f.state==='hitstun'&&f.stateTime>=(f.kind==='boss'?.13:.22))this.state(f,'idle');if(f.state==='knockdown'&&f.stateTime>=.72)this.state(f,f.health>0?'getup':'ko');if(f.state==='getup'&&f.stateTime>=.42)this.state(f,'idle');if(f.state==='attack'&&f.attack){const s=ATTACKS[f.attack];if(!f.attackHit&&f.stateTime>=s.activeFrom&&f.stateTime<=s.activeTo){const target=f.kind==='player'?this.closestTarget(f):this.player;if(target&&this.hit(f,target,s))f.attackHit=true}if(f.stateTime>=s.duration){f.attack=undefined;this.state(f,'idle')}}}
 private closestTarget(f:Fighter){let best:Fighter|undefined,dist=Infinity;for(const e of this.enemies){if(e.state==='ko')continue;const d=Math.abs(e.x-f.x)+Math.abs(e.y-f.y)*1.4;if(d<dist){best=e;dist=d}}return best}
 private playerUpdate(){const f=this.player;if(this.phase==='bossIntro'||this.phase==='complete'||['hitstun','knockdown','getup','ko','attack'].includes(f.state))return;if(this.consume('KeyZ')){f.comboStep=f.comboWindow>0?f.comboStep%3+1:1;this.attack(f,f.comboStep===1?'jab':f.comboStep===2?'cross':'finisher');f.comboWindow=.62;return}if(this.consume('KeyX')){this.attack(f,'finisher');f.comboStep=0;return}let dx=0,dy=0;if(this.down('ArrowLeft'))dx--;if(this.down('ArrowRight'))dx++;if(this.down('ArrowUp'))dy--;if(this.down('ArrowDown'))dy++;if(dx)f.facing=dx>0?1:-1;f.vx=dx*285;f.vy=dy*190;this.locomotion(f,dx!==0||dy!==0?'walk':'idle')}
 private enemyUpdate(f:Fighter,dt:number){if(['attack','hitstun','knockdown','getup','ko'].includes(f.state))return;const dx=this.player.x-f.x,dy=this.player.y-f.y;f.facing=dx>=0?1:-1;f.think-=dt;const boss=f.kind==='boss';if(Math.abs(dx)<(boss?126:102)&&Math.abs(dy)<(boss?45:36)&&f.think<=0){this.attack(f,boss?'boss':'enemy');f.think=(boss?.55:.85)+Math.random()*(boss?.45:.65);return}const crowd=this.enemies.filter(e=>e!==f&&e.state!=='ko'&&Math.abs(e.x-f.x)<55&&Math.abs(e.y-f.y)<28).length;f.vx=Math.abs(dx)>(boss?104:88)?Math.sign(dx)*(boss?138:112-crowd*12):0;f.vy=Math.abs(dy)>14?Math.sign(dy)*(boss?108:96-crowd*8):0;this.locomotion(f,f.vx!==0||f.vy!==0?'walk':'idle')}
 private attack(f:Fighter,k:AttackKind){f.vx=f.vy=0;f.attack=k;f.attackHit=false;this.state(f,'attack')}
 private hit(a:Fighter,t:Fighter,s:AttackSpec){if(t.state==='ko'||t.state==='knockdown')return false;if((t.x-a.x)*a.facing<=0||Math.abs(t.x-a.x)>s.reach||Math.abs(t.y-a.y)>45)return false;const boss=t.kind==='boss';t.health=Math.max(0,t.health-(boss?Math.ceil(s.damage*.7):s.damage));t.hitFlash=.11;t.vx=a.facing*s.knockback*(boss?3:8);t.vy=0;const canKnock=s.knockdown&&!boss;this.state(t,canKnock||t.health<=0?'knockdown':'hitstun');this.freezeTime=s.knockdown?.075:.045;this.shakeTime=s.knockdown?.16:.08;return true}
 private integrate(f:Fighter,dt:number){f.x+=f.vx*dt;f.y+=f.vy*dt;if(f.state==='hitstun'||f.state==='knockdown')f.vx*=Math.pow(.015,dt);else if(f.state!=='walk'){f.vx=f.vy=0}let minX=70,maxX=2230;if(this.phase==='combat'){const e=ENCOUNTERS[this.encounterIndex];minX=e.left;maxX=e.right}else if(this.phase==='bossIntro'||this.phase==='boss'){minX=1720;maxX=2230}f.x=Math.max(minX,Math.min(maxX,f.x));f.y=Math.max(350,Math.min(610,f.y))}private state(f:Fighter,s:FighterState){if(f.state!==s){f.state=s;f.stateTime=0}}private locomotion(f:Fighter,s:'idle'|'walk'){if(f.state==='idle'||f.state==='walk')this.state(f,s)}
 private render(){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.clearRect(0,0,w,h);c.save();if(this.shakeTime>0)c.translate((Math.random()-.5)*8,(Math.random()-.5)*5);this.backdrop();const actors=[this.player,...this.enemies].sort((a,b)=>a.y-b.y);for(const f of actors)this.draw(f);c.restore();this.hud();if(this.phase==='clear'||(this.phase==='travel'&&this.encounterIndex===0&&this.player.x<450))this.drawGo();if(this.phase==='bossIntro')this.drawBossIntro()}
 private backdrop(){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.fillStyle='#08101d';c.fillRect(0,0,w,h);c.save();c.translate(-this.cameraX*.18,0);c.fillStyle='#111b2c';for(let x=-100;x<2700;x+=210){const bh=120+(Math.abs(x)%170);c.fillRect(x,120,160,bh);c.fillStyle='#d48d35';for(let wy=145;wy<260;wy+=38)for(let wx=x+20;wx<x+140;wx+=45)c.fillRect(wx,wy,18,14);c.fillStyle='#111b2c'}c.restore();c.save();c.translate(-this.cameraX,0);c.fillStyle='#342e2b';c.fillRect(0,315,2300,405);c.fillStyle='#16191d';c.fillRect(0,330,2300,115);c.fillStyle='#50545a';c.fillRect(0,445,2300,275);c.strokeStyle='#73777b';c.lineWidth=4;for(let x=80;x<2300;x+=260){c.beginPath();c.moveTo(x,555);c.lineTo(x+120,555);c.stroke()}for(let x=220;x<2200;x+=520){c.fillStyle='#27211c';c.fillRect(x,380,65,65);c.fillStyle='#543a28';c.fillRect(x+7,387,51,51)}if(this.phase==='combat'){const e=ENCOUNTERS[this.encounterIndex];c.fillStyle='rgba(235,54,54,.25)';c.fillRect(e.left-8,340,16,280);c.fillRect(e.right-8,340,16,280)}if(this.phase==='bossIntro'||this.phase==='boss'){c.fillStyle='rgba(235,54,54,.28)';c.fillRect(1712,340,16,280)}c.restore()}
 private hud(){const c=this.ctx,w=this.canvas.width;this.bar(28,30,330,this.player.health/100,'ALEX');const target=this.closestTarget(this.player);c.textAlign='center';c.font='900 24px system-ui';c.fillStyle='#fff';let label=this.phase==='complete'?'STAGE 1 CLEAR!':this.phase==='bossIntro'?'WARNING!':this.phase==='boss'?'BOSS FIGHT':this.phase==='combat'?`FIGHT ${this.encounterIndex+1}/3  •  ${this.enemies.filter(e=>e.state!=='ko').length} NEMICI`:`STAGE 1  •  ZONA ${Math.min(this.encounterIndex+1,3)}/3`;c.fillText(label,w/2,48);c.textAlign='left';if(target)this.bar(w-318,30,290,target.health/target.maxHealth,target.kind==='boss'?'BRUNO':'THUG')}
 private drawGo(){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;if(Math.floor(performance.now()/220)%2!==0)return;c.save();c.textAlign='center';c.textBaseline='middle';c.font='1000 76px system-ui';c.lineWidth=10;c.strokeStyle='#111';c.fillStyle='#ffd83d';c.strokeText('GO  →',w*.76,h*.42);c.fillText('GO  →',w*.76,h*.42);c.restore()}
 private drawBossIntro(){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.save();c.fillStyle='rgba(0,0,0,.48)';c.fillRect(0,h*.32,w,h*.25);c.textAlign='center';c.textBaseline='middle';c.font='1000 58px system-ui';c.lineWidth=9;c.strokeStyle='#170000';c.fillStyle='#ff3c32';c.strokeText('WARNING!',w/2,h*.4);c.fillText('WARNING!',w/2,h*.4);c.font='900 30px system-ui';c.fillStyle='#fff';c.strokeText('BRUNO  •  THE ENFORCER',w/2,h*.49);c.fillText('BRUNO  •  THE ENFORCER',w/2,h*.49);c.restore()}
 private bar(x:number,y:number,w:number,r:number,l:string){const c=this.ctx;c.font='800 18px system-ui';c.fillStyle='#fff';c.fillText(l,x,y-6);c.fillStyle='#210e12';c.fillRect(x,y,w,16);c.fillStyle=r>.3?'#e64a42':'#f0b13d';c.fillRect(x,y,w*r,16);c.strokeStyle='#fff';c.strokeRect(x,y,w,16)}
 private frameIndex(f:Fighter){if(f.state==='walk')return Math.floor(f.stateTime*8)%2;if(f.state==='attack')return f.attack==='jab'?2:f.attack==='cross'||f.attack==='enemy'||f.attack==='boss'?3:4;if(f.state==='hitstun')return 5;if(f.state==='knockdown'||f.state==='ko')return 6;if(f.state==='getup')return 7;return 0}
 private draw(f:Fighter){const c=this.ctx,img=this.sprites[f.kind==='boss'?'enemy':f.kind],sx=f.x-this.cameraX,base=f.kind==='boss'?156:128,s=(f.kind==='boss'?1.13:.9)+((f.y-350)/260)*.18,d=base*s;if(sx<-130||sx>this.canvas.width+130)return;c.save();c.fillStyle='rgba(0,0,0,.4)';c.beginPath();c.ellipse(sx,f.y+4,(f.kind==='boss'?52:38)*s,10*s,0,0,Math.PI*2);c.fill();if(f.facing<0){c.translate(sx*2,0);c.scale(-1,1)}if(f.state==='ko')c.globalAlpha=.55;else if(f.hitFlash>0)c.globalAlpha=.55;if(img.complete&&img.naturalWidth)c.drawImage(img,this.frameIndex(f)*128,0,128,128,sx-d/2,f.y-d,d,d);c.restore()}
}
