type FighterKind='player'|'enemy'|'ripper'|'boss';
type FighterState='idle'|'walk'|'jump'|'attack'|'grab'|'grabbed'|'hitstun'|'knockdown'|'getup'|'ko';
type AttackKind='jab'|'cross'|'finisher'|'run'|'jump'|'enemy'|'ripper'|'boss';
type Phase='travel'|'combat'|'clear'|'bossIntro'|'boss'|'stageTransition'|'complete'|'gameOver';
type Fighter={kind:FighterKind;x:number;y:number;z:number;vx:number;vy:number;vz:number;width:number;height:number;health:number;maxHealth:number;facing:1|-1;state:FighterState;stateTime:number;attack?:AttackKind;attackHit:boolean;comboStep:number;comboWindow:number;hitFlash:number;think:number;id:number;invuln:number;strafe:number};
type AttackSpec={duration:number;activeFrom:number;activeTo:number;damage:number;near:number;reach:number;lane:number;knockback:number;knockdown:boolean;hitStop:number;shake:number};
type Encounter={trigger:number;left:number;right:number;count:number};
type Particle={x:number;y:number;vx:number;vy:number;life:number;maxLife:number;size:number;kind:'spark'|'dust'};
type Prop={x:number;y:number;hp:number;broken:boolean;kind:'crate'|'barrel'};
type RenderItem={kind:'fighter';y:number;fighter:Fighter}|{kind:'prop';y:number;prop:Prop};

const ATTACKS:Record<AttackKind,AttackSpec>={
 jab:{duration:.28,activeFrom:.105,activeTo:.15,damage:8,near:24,reach:82,lane:30,knockback:8,knockdown:false,hitStop:.035,shake:.05},
 cross:{duration:.34,activeFrom:.135,activeTo:.195,damage:10,near:26,reach:94,lane:32,knockback:12,knockdown:false,hitStop:.045,shake:.07},
 finisher:{duration:.5,activeFrom:.2,activeTo:.29,damage:18,near:30,reach:112,lane:36,knockback:38,knockdown:true,hitStop:.075,shake:.16},
 run:{duration:.44,activeFrom:.14,activeTo:.27,damage:22,near:22,reach:120,lane:38,knockback:48,knockdown:true,hitStop:.08,shake:.18},
 jump:{duration:.48,activeFrom:.12,activeTo:.3,damage:20,near:22,reach:112,lane:40,knockback:42,knockdown:true,hitStop:.075,shake:.16},
 enemy:{duration:.5,activeFrom:.19,activeTo:.255,damage:9,near:22,reach:72,lane:32,knockback:18,knockdown:false,hitStop:.035,shake:.05},
 ripper:{duration:.42,activeFrom:.15,activeTo:.22,damage:12,near:24,reach:82,lane:34,knockback:20,knockdown:false,hitStop:.04,shake:.06},
 boss:{duration:.66,activeFrom:.25,activeTo:.345,damage:16,near:26,reach:108,lane:40,knockback:30,knockdown:false,hitStop:.06,shake:.12}
};
const ENCOUNTERS:Encounter[]=[{trigger:520,left:360,right:1050,count:2},{trigger:1250,left:1080,right:1780,count:3},{trigger:1900,left:1730,right:2230,count:4}];
const LANES={1:{top:505,bottom:610},2:{top:465,bottom:610}} as const;

export class Game{
 private readonly ctx:CanvasRenderingContext2D;
 private readonly keys=new Set<string>();private readonly virtualKeys=new Set<string>();private readonly pressed=new Set<string>();
 private previous=performance.now();private accumulator=0;private readonly fixedStep=1/60;private paused=false;
 private freezeTime=0;private shakeTime=0;private cameraX=0;private nextId=1;private stage:1|2=1;private encounterIndex=0;private phase:Phase='travel';
 private goTimer=2.6;private introTimer=0;private transitionTimer=0;private combo=0;private comboTimer=0;private particles:Particle[]=[];private props:Prop[]=[];private grabbed?:Fighter;
 private lastRightTap=-9;private lastLeftTap=-9;private runDir:1|-1=1;private runTimer=0;private audio?:AudioContext;
 private readonly sprites={player:new Image(),enemy:new Image(),ripper:new Image(),bruno:new Image(),dockMaster:new Image()};
 private readonly stage1Art=new Image();private readonly stage2Art=new Image();
 private readonly player:Fighter=this.make('player',180,540,1);private enemies:Fighter[]=[];

 constructor(private readonly canvas:HTMLCanvasElement){
  const c=canvas.getContext('2d');if(!c)throw new Error('Canvas 2D unavailable');this.ctx=c;c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';
  this.sprites.player.src='/assets/fighters/alex.svg';this.sprites.enemy.src='/assets/fighters/thug.svg';this.sprites.ripper.src='/assets/fighters/ripper.svg';this.sprites.bruno.src='/assets/fighters/bruno.svg';this.sprites.dockMaster.src='/assets/fighters/dock-master.svg';this.stage1Art.src='/assets/stages/stage1-street.svg';this.stage2Art.src='/assets/stages/stage2-docks.svg';
  window.addEventListener('keydown',e=>{this.ensureAudio();if(!this.keys.has(e.code))this.pressed.add(e.code);this.keys.add(e.code);if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault()});
  window.addEventListener('keyup',e=>this.keys.delete(e.code));this.resetProps();
 }
 start(){requestAnimationFrame(this.frame)}
 setVirtualKey(code:string,down:boolean){this.ensureAudio();if(down&&!this.virtualKeys.has(code))this.pressed.add(code);if(down)this.virtualKeys.add(code);else this.virtualKeys.delete(code)}
 resetInput(){this.keys.clear();this.virtualKeys.clear();this.pressed.clear();this.runTimer=0}
 setPaused(value:boolean){this.paused=value;this.resetInput();this.accumulator=0;this.previous=performance.now();if(!value&&this.audio?.state==='suspended')void this.audio.resume().catch(()=>{})}
 private make(kind:FighterKind,x:number,y:number,facing:1|-1):Fighter{const boss=kind==='boss',ripper=kind==='ripper',hp=boss?(this.stage===1?260:320):ripper?135:100;return{kind,x,y,z:0,vx:0,vy:0,vz:0,width:boss?78:ripper?64:kind==='player'?58:62,height:boss?142:ripper?120:kind==='player'?112:116,health:hp,maxHealth:hp,facing,state:'idle',stateTime:0,attackHit:false,comboStep:0,comboWindow:0,hitFlash:0,think:.35+Math.random()*.5,id:this.nextId++,invuln:0,strafe:Math.random()<.5?-1:1}}
 private down(c:string){return this.keys.has(c)||this.virtualKeys.has(c)}private consume(c:string){const h=this.pressed.has(c);this.pressed.delete(c);return h}
 private ensureAudio(){if(!this.audio)try{this.audio=new AudioContext()}catch{}else if(this.audio.state==='suspended')void this.audio.resume().catch(()=>{})}
 private sound(freq:number,d=.05,type:OscillatorType='square',vol=.025){if(!this.audio||this.audio.state!=='running')return;const o=this.audio.createOscillator(),g=this.audio.createGain(),t=this.audio.currentTime;o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(40,freq*.55),t+d);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(this.audio.destination);o.start(t);o.stop(t+d)}
 private frame=(now:number)=>{const d=Math.min((now-this.previous)/1000,.1);this.previous=now;if(!this.paused){this.accumulator+=d;while(this.accumulator>=this.fixedStep){this.update(this.fixedStep);this.accumulator-=this.fixedStep}}this.render();requestAnimationFrame(this.frame)};
 private update(dt:number){
  this.updateParticles(dt);this.comboTimer=Math.max(0,this.comboTimer-dt);if(this.comboTimer<=0)this.combo=0;this.runTimer=Math.max(0,this.runTimer-dt);
  if(this.freezeTime>0){this.freezeTime-=dt;this.pressed.clear();return}this.shakeTime=Math.max(0,this.shakeTime-dt);this.timers(this.player,dt);for(const e of this.enemies)this.timers(e,dt);
  if(this.phase==='gameOver'||this.phase==='complete'){if(this.consume('Space')||this.consume('KeyZ')||this.consume('KeyX'))this.restart();this.pressed.clear();return}
  if(this.phase==='stageTransition'){this.transitionTimer-=dt;if(this.transitionTimer<=0)this.startStage2();this.pressed.clear();return}
  if(this.phase==='bossIntro'){this.introTimer-=dt;if(this.introTimer<=0)this.phase='boss'}
  this.playerUpdate();if(this.phase!=='bossIntro')for(const e of this.enemies)this.enemyUpdate(e,dt);
  this.integrate(this.player,dt);this.updateAir(this.player,dt);for(const e of this.enemies)this.integrate(e,dt);this.resolveCrowd();this.clampAll();this.syncGrab();this.clampAll();this.checkThrownCollisions();this.checkProps();
  if(this.player.state==='ko'){this.phase='gameOver';this.releaseGrab()}
  if(this.phase==='travel'&&this.encounterIndex<ENCOUNTERS.length&&this.player.x>=ENCOUNTERS[this.encounterIndex].trigger)this.beginEncounter();
  if(this.phase==='combat'&&this.enemies.length>0&&this.enemies.every(e=>e.state==='ko'))this.finishEncounter();
  if(this.phase==='clear'){this.goTimer=Math.max(0,this.goTimer-dt);if(this.goTimer<=0)this.phase='travel'}
  if(this.encounterIndex>=ENCOUNTERS.length&&this.phase==='travel'&&this.player.x>=2180)this.beginBoss();
  if(this.phase==='boss'&&this.enemies.length&&this.enemies.every(e=>e.state==='ko'))this.finishBoss();
  this.cameraX=Math.max(0,Math.min(2300-this.canvas.width,this.player.x-this.canvas.width*.42));this.pressed.clear();
 }
 private resetPlayerTransient(invuln=0){this.releaseGrab();this.player.z=0;this.player.vx=0;this.player.vy=0;this.player.vz=0;this.player.attack=undefined;this.player.attackHit=false;this.player.comboStep=0;this.player.comboWindow=0;this.player.hitFlash=0;this.player.invuln=invuln;this.player.state='idle';this.player.stateTime=0;this.runTimer=0;this.lastLeftTap=this.lastRightTap=-9;this.freezeTime=0;this.shakeTime=0;this.resetInput()}
 private restart(){this.stage=1;this.encounterIndex=0;this.phase='travel';this.player.health=this.player.maxHealth;this.player.x=180;this.player.y=540;this.resetPlayerTransient(1);this.enemies=[];this.cameraX=0;this.combo=0;this.comboTimer=0;this.particles=[];this.goTimer=2.6;this.resetProps();this.sound(420,.18,'sawtooth',.035)}
 private startStage2(){this.stage=2;this.encounterIndex=0;this.phase='travel';this.player.x=180;this.player.y=520;this.player.health=Math.min(this.player.maxHealth,this.player.health+35);this.resetPlayerTransient(.7);this.cameraX=0;this.enemies=[];this.goTimer=2.8;this.combo=0;this.comboTimer=0;this.particles=[];this.resetProps()}
 private resetProps(){this.props=this.stage===1?[{x:870,y:600,hp:28,broken:false,kind:'crate'},{x:1580,y:595,hp:32,broken:false,kind:'barrel'}]:[{x:780,y:595,hp:28,broken:false,kind:'crate'},{x:1500,y:585,hp:32,broken:false,kind:'barrel'}]}
 private updateAir(f:Fighter,dt:number){if(f.z<=0&&f.vz<=0)return;f.z+=f.vz*dt;f.vz-=1300*dt;if(f.z<=0){f.z=0;f.vz=0;if(f.state==='jump'||(f.state==='attack'&&f.attack==='jump')){f.attack=undefined;this.state(f,'idle');this.burst(f.x,f.y);this.sound(90,.035,'triangle',.015)}}}
 private updateParticles(dt:number){for(const p of this.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=p.kind==='spark'?520*dt:-20*dt;p.vx*=Math.pow(.12,dt)}this.particles=this.particles.filter(p=>p.life>0)}
 private burst(x:number,y:number,strong=false){const n=strong?14:8;for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=(strong?150:100)*(.5+Math.random());this.particles.push({x,y:y-55,vx:Math.cos(a)*s,vy:Math.sin(a)*s-45,life:.18+Math.random()*.16,maxLife:.34,size:2+Math.random()*5,kind:'spark'})}}
 private beginEncounter(){const e=ENCOUNTERS[this.encounterIndex];this.phase='combat';this.enemies=[];this.grabbed=undefined;for(let i=0;i<e.count;i++){const side=i%2===0?1:-1,x=Math.max(e.left+100,Math.min(e.right-100,this.player.x+side*(300+i*65))),y=(this.stage===1?525:500)+(i%3)*38,kind:FighterKind=this.stage===2&&((i+this.encounterIndex)%2===1)?'ripper':'enemy';this.enemies.push(this.make(kind,x,y,side>0?-1:1))}this.sound(170,.15,'sawtooth',.025)}
 private finishEncounter(){this.encounterIndex++;this.phase='clear';this.goTimer=2.6;this.combo=0;this.grabbed=undefined;this.player.health=Math.min(this.player.maxHealth,this.player.health+8);this.sound(660,.16,'square',.025)}
 private beginBoss(){this.phase='bossIntro';this.introTimer=2.3;this.player.x=Math.min(this.player.x,2070);this.resetPlayerTransient(.4);this.enemies=[this.make('boss',2220,this.stage===1?550:530,-1)];this.sound(80,.45,'sawtooth',.05)}
 private finishBoss(){this.sound(520,.35,'square',.04);if(this.stage===1){this.phase='stageTransition';this.transitionTimer=3.2;this.enemies=[]}else this.phase='complete'}
 private targetInHitbox(a:Fighter,s:AttackSpec){let best:Fighter|undefined,dist=Infinity;for(const e of this.enemies){if(['ko','knockdown','grabbed'].includes(e.state))continue;const forward=(e.x-a.x)*a.facing,lane=Math.abs(e.y-a.y);if(forward<s.near||forward>s.reach||lane>s.lane)continue;const d=forward+lane*1.5;if(d<dist){best=e;dist=d}}return best}
 private timers(f:Fighter,dt:number){f.stateTime+=dt;f.hitFlash=Math.max(0,f.hitFlash-dt);f.invuln=Math.max(0,f.invuln-dt);f.comboWindow=Math.max(0,f.comboWindow-dt);if(f.comboWindow<=0&&f.state!=='attack')f.comboStep=0;if(f.state==='grabbed'||f.state==='jump')return;if(f.state==='grab'&&f.stateTime>=1.25)this.releaseGrab();if(f.state==='hitstun'&&f.stateTime>=(f.kind==='boss'?.16:.22))this.state(f,'idle');if(f.state==='knockdown'&&f.stateTime>=.72){if(f.health>0){f.invuln=Math.max(f.invuln,.75);this.state(f,'getup')}else this.state(f,'ko')}if(f.state==='getup'){f.invuln=Math.max(f.invuln,.08);if(f.stateTime>=.42){f.invuln=Math.max(f.invuln,.18);this.state(f,'idle')}}if(f.state==='attack'&&f.attack){const s=ATTACKS[f.attack];if(!f.attackHit&&f.stateTime>=s.activeFrom&&f.stateTime<=s.activeTo){const target=f.kind==='player'?this.targetInHitbox(f,s):this.player;if(target&&this.hit(f,target,s))f.attackHit=true}if(f.stateTime>=s.duration&&f.attack!=='jump'){f.attack=undefined;this.state(f,'idle')}}}
 private closestTarget(f:Fighter){let best:Fighter|undefined,dist=Infinity;for(const e of this.enemies){if(e.state==='ko'||e.state==='grabbed')continue;const d=Math.abs(e.x-f.x)+Math.abs(e.y-f.y)*1.4;if(d<dist){best=e;dist=d}}return best}
 private grabTarget(){let best:Fighter|undefined,dist=Infinity;for(const e of this.enemies){if(e.kind==='boss'||!['idle','walk','hitstun'].includes(e.state))continue;const dx=(e.x-this.player.x)*this.player.facing,d=Math.abs(e.x-this.player.x)+Math.abs(e.y-this.player.y)*1.5;if(dx>0&&dx<72&&Math.abs(e.y-this.player.y)<34&&d<dist){best=e;dist=d}}return best}
 private tryGrab(){const t=this.grabTarget();if(!t)return false;this.grabbed=t;t.vx=t.vy=0;this.state(t,'grabbed');this.player.vx=this.player.vy=0;this.state(this.player,'grab');this.syncGrab();return true}
 private syncGrab(){if(!this.grabbed)return;if(this.grabbed.state!=='grabbed'||this.player.state!=='grab'){this.grabbed=undefined;return}this.grabbed.x=this.player.x+this.player.facing*48;this.grabbed.y=this.player.y+2;this.grabbed.facing=(this.player.facing*-1) as 1|-1}
 private releaseGrab(){if(!this.grabbed)return;const t=this.grabbed;this.grabbed=undefined;if(t.state==='grabbed')this.state(t,'idle');if(this.player.state==='grab')this.state(this.player,'idle')}
 private throwGrab(){if(!this.grabbed)return;const t=this.grabbed;this.grabbed=undefined;t.health=Math.max(0,t.health-24);t.vx=this.player.facing*520;t.hitFlash=.12;this.state(t,'knockdown');this.state(this.player,'attack');this.player.attack='finisher';this.player.attackHit=true;this.burst(t.x,t.y,true);this.combo++;this.comboTimer=1.2;this.freezeTime=.08;this.shakeTime=.18;this.sound(105,.1,'sawtooth',.05)}
 private playerUpdate(){const f=this.player;if(this.phase==='bossIntro'||this.phase==='stageTransition'||['hitstun','knockdown','getup','ko'].includes(f.state))return;if(f.state==='grab'){if(this.consume('KeyX')||this.consume('KeyZ'))this.throwGrab();return}if(f.z>0){let dx=0,dy=0;if(this.down('ArrowLeft'))dx--;if(this.down('ArrowRight'))dx++;if(this.down('ArrowUp'))dy--;if(this.down('ArrowDown'))dy++;if(dx)f.facing=dx>0?1:-1;if(f.state==='jump'){f.vx=dx*245;f.vy=dy*145;if(this.consume('KeyX')||this.consume('KeyZ')){f.attack='jump';f.attackHit=false;this.state(f,'attack')}}return}if(f.state==='attack')return;if(this.consume('Space')){f.z=.1;f.vz=560;this.state(f,'jump');this.sound(180,.06,'triangle',.018);return}const now=performance.now()/1000;if(this.consume('ArrowRight')){if(now-this.lastRightTap<.28){this.runDir=1;this.runTimer=.72}this.lastRightTap=now}if(this.consume('ArrowLeft')){if(now-this.lastLeftTap<.28){this.runDir=-1;this.runTimer=.72}this.lastLeftTap=now}if(this.consume('KeyX')){if(this.tryGrab())return;if(this.runTimer>0){f.facing=this.runDir;this.attack(f,'run');f.vx=this.runDir*460;return}this.attack(f,'finisher');f.comboStep=0;return}if(this.consume('KeyZ')){if(this.tryGrab())return;if(this.runTimer>0){f.facing=this.runDir;this.attack(f,'run');f.vx=this.runDir*460;return}f.comboStep=f.comboWindow>0?f.comboStep%3+1:1;this.attack(f,f.comboStep===1?'jab':f.comboStep===2?'cross':'finisher');f.comboWindow=.62;return}let dx=0,dy=0;if(this.down('ArrowLeft'))dx--;if(this.down('ArrowRight'))dx++;if(this.down('ArrowUp'))dy--;if(this.down('ArrowDown'))dy++;if(dx&&dy){dx*=.707;dy*=.707}if(dx)f.facing=dx>0?1:-1;const targetX=this.runTimer>0&&Math.sign(dx)===this.runDir?dx*410:dx*285,targetY=dy*(this.runTimer>0?145:190),blend=.28;f.vx+=(targetX-f.vx)*blend;f.vy+=(targetY-f.vy)*blend;if(!dx)f.vx*=.68;if(!dy)f.vy*=.68;this.locomotion(f,Math.abs(f.vx)>8||Math.abs(f.vy)>8?'walk':'idle')}
 private enemyUpdate(f:Fighter,dt:number){if(['attack','grabbed','hitstun','knockdown','getup','ko'].includes(f.state))return;const dx=this.player.x-f.x,dy=this.player.y-f.y;f.facing=dx>=0?1:-1;f.think-=dt;const boss=f.kind==='boss',ripper=f.kind==='ripper',kind:AttackKind=boss?'boss':ripper?'ripper':'enemy',spec=ATTACKS[kind],hp=f.health/f.maxHealth;if(boss&&hp<.5&&f.think<=0&&Math.abs(dx)<190){this.attack(f,'boss');f.vx=f.facing*(this.stage===2?250:205);f.think=.42+Math.random()*.32;return}const attackers=this.enemies.filter(e=>e!==f&&e.state==='attack').length;if(this.player.z<75&&Math.abs(dx)<spec.reach+8&&Math.abs(dy)<spec.lane+3&&f.think<=0&&attackers<(boss?2:1)){this.attack(f,kind);f.think=(boss?.5:ripper?.65:.9)+Math.random()*.5;return}const crowd=this.enemies.filter(e=>e!==f&&e.state!=='ko'&&Math.abs(e.x-f.x)<62&&Math.abs(e.y-f.y)<34).length,speed=boss?145:ripper?160:118;let tx=Math.abs(dx)>spec.reach-6?Math.sign(dx)*speed:0,ty=Math.abs(dy)>spec.lane*.6?Math.sign(dy)*(boss?105:ripper?120:98):0;if(!tx&&Math.abs(dy)<22&&Math.abs(dx)<150){ty=f.strafe*(boss?75:92);if(Math.random()<dt*.7)f.strafe*=-1}f.vx=tx*(crowd?.72:1);f.vy=ty*(crowd?.7:1);this.locomotion(f,f.vx!==0||f.vy!==0?'walk':'idle')}
 private attack(f:Fighter,k:AttackKind){f.vx=f.vy=0;f.attack=k;f.attackHit=false;this.state(f,'attack')}
 private hit(a:Fighter,t:Fighter,s:AttackSpec){if(t.invuln>0||['ko','knockdown','getup','grabbed'].includes(t.state))return false;if(a.kind!=='player'&&t.z>75)return false;if(a.attack==='jump'&&(a.z<28||a.z>125))return false;const forward=(t.x-a.x)*a.facing;if(forward<s.near||forward>s.reach||Math.abs(t.y-a.y)>s.lane)return false;const boss=t.kind==='boss',strong=s.knockdown||a.kind==='boss';t.health=Math.max(0,t.health-(boss?Math.ceil(s.damage*.7):s.damage));t.hitFlash=.11;t.vx=a.facing*s.knockback*(boss?3:8);const canKnock=s.knockdown&&!boss;this.state(t,canKnock||t.health<=0?'knockdown':'hitstun');this.freezeTime=s.hitStop;this.shakeTime=s.shake;this.burst(a.x+a.facing*Math.min(s.reach*.82,Math.max(s.near,forward)),(a.y+t.y)/2,strong);this.sound(strong?90:150,strong?.1:.055,strong?'sawtooth':'square',strong?.05:.025);if(a.kind==='player'){this.combo++;this.comboTimer=1.15}else{this.combo=0;this.comboTimer=0;this.releaseGrab()}return true}
 private checkThrownCollisions(){for(const thrown of this.enemies){if(thrown.state!=='knockdown'||Math.abs(thrown.vx)<180)continue;for(const other of this.enemies){if(other===thrown||['ko','knockdown','grabbed'].includes(other.state))continue;if(Math.abs(other.x-thrown.x)<72&&Math.abs(other.y-thrown.y)<38){other.health=Math.max(0,other.health-14);other.vx=Math.sign(thrown.vx)*260;this.state(other,'knockdown');this.burst(other.x,other.y,true);this.combo++;this.comboTimer=1.2;thrown.vx*=.55}}}}
 private checkProps(){if(this.player.state!=='attack'||!this.player.attack||this.player.attackHit)return;const s=ATTACKS[this.player.attack];if(this.player.stateTime<s.activeFrom||this.player.stateTime>s.activeTo)return;for(const p of this.props){if(p.broken)continue;const forward=(p.x-this.player.x)*this.player.facing;if(forward>=10&&forward<=s.reach+20&&Math.abs(p.y-this.player.y)<45){p.hp-=s.damage;this.player.attackHit=true;this.burst(p.x,p.y,true);if(p.hp<=0){p.broken=true;this.player.health=Math.min(this.player.maxHealth,this.player.health+12)}break}}}
 private resolveCrowd(){const all=[this.player,...this.enemies.filter(e=>e.state!=='ko'&&e.state!=='grabbed')];for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++){const a=all[i],b=all[j],dx=b.x-a.x,dy=b.y-a.y;if(Math.abs(dx)<34&&Math.abs(dy)<24&&a.z<30&&b.z<30){const push=(34-Math.abs(dx))*.09,dir=dx===0?(a.id<b.id?1:-1):Math.sign(dx);if(a.state!=='attack')a.x-=dir*push;if(b.state!=='attack')b.x+=dir*push;const py=(24-Math.abs(dy))*.05,yd=dy===0?1:Math.sign(dy);a.y-=yd*py;b.y+=yd*py}}}
 private bounds(f:Fighter){let minX=70,maxX=2230;if(this.phase==='combat'){const e=ENCOUNTERS[this.encounterIndex];minX=e.left;maxX=e.right}else if(this.phase==='bossIntro'||this.phase==='boss'){minX=1720;maxX=2230}const lane=LANES[this.stage];f.x=Math.max(minX,Math.min(maxX,f.x));f.y=Math.max(lane.top,Math.min(lane.bottom,f.y))}
 private clampAll(){this.bounds(this.player);for(const e of this.enemies)this.bounds(e)}
 private integrate(f:Fighter,dt:number){f.x+=f.vx*dt;f.y+=f.vy*dt;if(f.state==='hitstun'||f.state==='knockdown')f.vx*=Math.pow(.15,dt);else if(f.state!=='walk'&&f.z<=0&&!(f.kind==='player'&&f.state==='attack'&&f.attack==='run')&&!(f.kind==='boss'&&f.state==='attack')){f.vx=f.vy=0}this.bounds(f)}
 private state(f:Fighter,s:FighterState){if(f.state!==s){f.state=s;f.stateTime=0}}private locomotion(f:Fighter,s:'idle'|'walk'){if(f.state==='idle'||f.state==='walk')this.state(f,s)}
 private render(){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.clearRect(0,0,w,h);c.save();if(this.shakeTime>0)c.translate((Math.random()-.5)*8,(Math.random()-.5)*5);this.backdrop();const items:RenderItem[]=[...this.props.filter(p=>!p.broken).map((prop):RenderItem=>({kind:'prop',y:prop.y,prop})),...[this.player,...this.enemies].map((fighter):RenderItem=>({kind:'fighter',y:fighter.y,fighter}))];items.sort((a,b)=>a.y-b.y);for(const item of items){if(item.kind==='fighter')this.draw(item.fighter);else this.drawProp(item.prop)}this.drawParticles();c.restore();this.hud();if(this.phase==='clear'||(this.phase==='travel'&&this.encounterIndex===0&&this.player.x<450))this.drawGo();if(this.phase==='bossIntro')this.drawBossIntro();if(this.phase==='stageTransition')this.drawTransition();if(this.phase==='gameOver')this.drawOverlay('GAME OVER','TOCCA JUMP / PUNCH / KICK PER RIPARTIRE');if(this.phase==='complete')this.drawOverlay('STREETBRAWL CLEAR!','TOCCA UN TASTO AZIONE PER UNA NUOVA PARTITA');if(this.paused)this.drawOverlay('PAUSA','TORNA AL GIOCO PER RIPRENDERE');if(this.combo>=2)this.drawCombo()}
 private drawProp(p:Prop){const c=this.ctx,x=p.x-this.cameraX;c.save();c.translate(x,p.y);c.fillStyle=p.kind==='crate'?'#6d4326':'#4e6570';c.fillRect(p.kind==='crate'?-30:-23,p.kind==='crate'?-50:-55,p.kind==='crate'?60:46,p.kind==='crate'?50:55);c.restore()}
 private drawParticles(){const c=this.ctx;for(const p of this.particles){const a=Math.max(0,p.life/p.maxLife);c.globalAlpha=Math.min(1,a);c.fillStyle=p.life>.16?'#fff4a8':'#ff7a2d';c.fillRect(p.x-this.cameraX-p.size/2,p.y-p.size/2,p.size,p.size)}c.globalAlpha=1}
 private backdrop(){const c=this.ctx,w=this.canvas.width,h=this.canvas.height,art=this.stage===1?this.stage1Art:this.stage2Art;c.fillStyle=this.stage===1?'#10131b':'#07131a';c.fillRect(0,0,w,h);if(art.complete&&art.naturalWidth)c.drawImage(art,this.cameraX,0,Math.min(w,2300-this.cameraX),720,0,0,Math.min(w,2300-this.cameraX),h)}
 private hud(){const c=this.ctx,w=this.canvas.width;this.bar(28,30,330,this.player.health/this.player.maxHealth,'ALEX');const target=this.closestTarget(this.player);c.textAlign='center';c.font='900 24px system-ui';c.fillStyle='#fff';const label=this.phase==='complete'?'STAGE 2 CLEAR!':this.phase==='stageTransition'?'STAGE 1 CLEAR!':this.phase==='bossIntro'?'WARNING!':this.phase==='boss'?'BOSS FIGHT':this.phase==='combat'?`FIGHT ${this.encounterIndex+1}/3  •  ${this.enemies.filter(e=>e.state!=='ko').length} NEMICI`:`STAGE ${this.stage}  •  ${this.stage===2?'DOCKS':'THE STREETS'}  •  ZONA ${Math.min(this.encounterIndex+1,3)}/3`;c.fillText(label,w/2,48);c.textAlign='left';if(target)this.bar(w-318,30,290,target.health/target.maxHealth,target.kind==='boss'?(this.stage===1?'BRUNO':'DOCK MASTER'):target.kind==='ripper'?'RIPPER':'THUG')}
 private drawCombo(){const c=this.ctx;c.save();c.translate(105,150);c.textAlign='center';c.lineWidth=8;c.strokeStyle='#101014';c.fillStyle=this.combo>=6?'#ff5b36':'#ffd83d';c.font='1000 50px system-ui';c.strokeText(`${this.combo} HIT`,0,0);c.fillText(`${this.combo} HIT`,0,0);c.restore()}
 private drawGo(){if(Math.floor(performance.now()/220)%2)return;const c=this.ctx;c.save();c.textAlign='center';c.font='1000 76px system-ui';c.lineWidth=10;c.strokeStyle='#111';c.fillStyle='#ffd83d';c.strokeText('GO  →',this.canvas.width*.76,this.canvas.height*.42);c.fillText('GO  →',this.canvas.width*.76,this.canvas.height*.42);c.restore()}
 private drawBossIntro(){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.save();c.fillStyle='rgba(0,0,0,.5)';c.fillRect(0,h*.32,w,h*.25);c.textAlign='center';c.font='1000 58px system-ui';c.fillStyle='#ff3c32';c.fillText('WARNING!',w/2,h*.42);c.font='900 30px system-ui';c.fillStyle='#fff';c.fillText(this.stage===1?'BRUNO • THE ENFORCER':'DOCK MASTER',w/2,h*.5);c.restore()}
 private drawTransition(){this.drawOverlay('STAGE 1 CLEAR!','NEXT: HARBOR DOCKS • NEW ENEMY: RIPPER')}
 private drawOverlay(title:string,sub:string){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.save();c.fillStyle='rgba(0,0,0,.72)';c.fillRect(0,0,w,h);c.textAlign='center';c.fillStyle='#ffd83d';c.font='1000 58px system-ui';c.fillText(title,w/2,h*.44);c.fillStyle='#fff';c.font='800 24px system-ui';c.fillText(sub,w/2,h*.53);c.restore()}
 private bar(x:number,y:number,w:number,r:number,l:string){const c=this.ctx;c.font='800 18px system-ui';c.fillStyle='#fff';c.fillText(l,x,y-6);c.fillStyle='#210e12';c.fillRect(x,y,w,16);c.fillStyle=r>.3?'#e64a42':'#f0b13d';c.fillRect(x,y,w*Math.max(0,r),16);c.strokeStyle='#fff';c.strokeRect(x,y,w,16)}
 private frameIndex(f:Fighter){if(f.state==='walk')return Math.floor(f.stateTime*8)%2;if(f.state==='jump')return 4;if(f.state==='grab'||f.state==='grabbed')return 2;if(f.state==='attack'&&f.attack){const s=ATTACKS[f.attack],strike=f.attack==='jab'?2:f.attack==='cross'||f.attack==='enemy'||f.attack==='ripper'||f.attack==='boss'?3:4;if(f.attack==='jump')return 4;if(f.stateTime<s.activeFrom*.65)return 0;if(f.stateTime<=s.activeTo+.035)return strike;return f.attack==='finisher'||f.attack==='run'?1:0}if(f.state==='hitstun')return 5;if(f.state==='knockdown'||f.state==='ko')return 6;if(f.state==='getup')return 7;return 0}
 private draw(f:Fighter){const c=this.ctx,img=f.kind==='player'?this.sprites.player:f.kind==='ripper'?this.sprites.ripper:f.kind==='boss'?(this.stage===1?this.sprites.bruno:this.sprites.dockMaster):this.sprites.enemy,sx=f.x-this.cameraX,base=f.kind==='boss'?156:128,s=(f.kind==='boss'?1.13:.9)+((f.y-465)/145)*.14,d=base*s;if(sx<-130||sx>this.canvas.width+130)return;c.save();c.fillStyle=`rgba(0,0,0,${Math.max(.15,.4-f.z/500)})`;c.beginPath();c.ellipse(sx,f.y+4,(f.kind==='boss'?52:38)*s,10*s,0,0,Math.PI*2);c.fill();if(f.facing<0){c.translate(sx*2,0);c.scale(-1,1)}if(f.state==='ko')c.globalAlpha=.55;else if(f.hitFlash>0)c.globalAlpha=.55;else if(f.invuln>0&&Math.floor(f.invuln*20)%2)c.globalAlpha=.45;if(img.complete&&img.naturalWidth)c.drawImage(img,this.frameIndex(f)*128,0,128,128,sx-d/2,f.y-d-f.z,d,d);c.restore()}
}
